### ISSUE TITLE
Review identity hash generation

### ISSUE THREAD

**Issue by torchello** [applandinc/scanner#113]
2 findings on the screenshot have the same `identity_hash`  but different messages.
![image](https://user-images.githubusercontent.com/897885/157096880-a3795a64-5bb0-424d-ba77-701a8d37150c.png)

Needs investigation. One of the ideas by @dustinbyrne:
```
Maybe the hash should be generated from a unique set of all the related event's identity hashes as well?
```

**Comment by kgilpin** [comment]
One thing that confuses me - the @appland/models#Event includes properties `identityHash` and `hash`. It seems that `identityHash` is used for a separate diff algorithm - `hash` is the right one to use for de-duplication.

It would be good to clarify this in the code, maybe by renaming `identityHash` and/or `hash`.
